# AI DECLARATION: Generated by Gemini 2.0

CC = gcc
CFLAGS = -Wall -pthread -O2
LDFLAGS = -pthread

SRC = src
OBJ = obj
BIN = bin

SERVER = $(BIN)/server
CLIENT_2COPY = $(BIN)/client_2copy
CLIENT_1COPY = $(BIN)/client_1copy
CLIENT_0COPY = $(BIN)/client_0copy

COMMON_OBJ = $(OBJ)/common.o

# Build everything
all: dirs $(SERVER) $(CLIENT_2COPY) $(CLIENT_1COPY) $(CLIENT_0COPY)

dirs:
	mkdir -p $(OBJ) $(BIN)

$(COMMON_OBJ): $(SRC)/common.c $(SRC)/common.h
	$(CC) $(CFLAGS) -c $(SRC)/common.c -o $(COMMON_OBJ)

$(SERVER): $(SRC)/server.c $(COMMON_OBJ)
	$(CC) $(CFLAGS) $(SRC)/server.c $(COMMON_OBJ) -o $(SERVER)

$(CLIENT_2COPY): $(SRC)/client_2copy.c $(COMMON_OBJ)
	$(CC) $(CFLAGS) $(SRC)/client_2copy.c $(COMMON_OBJ) -o $(CLIENT_2COPY)

$(CLIENT_1COPY): $(SRC)/client_1copy.c $(COMMON_OBJ)
	$(CC) $(CFLAGS) $(SRC)/client_1copy.c $(COMMON_OBJ) -o $(CLIENT_1COPY)

$(CLIENT_0COPY): $(SRC)/client_0copy.c $(COMMON_OBJ)
	$(CC) $(CFLAGS) $(SRC)/client_0copy.c $(COMMON_OBJ) -o $(CLIENT_0COPY)

clean:
	rm -rf $(OBJ) $(BIN)