#!/bin/bash
# AI DECLARATION: Generated by Gemini 2.0 to setup veth pairs and namespaces

# 1. Clean up old namespaces to ensure a fresh start
sudo ip netns del ns_server 2>/dev/null
sudo ip netns del ns_client 2>/dev/null

# 2. Create Namespaces (Think of these as two separate computers)
echo "Creating namespaces..."
sudo ip netns add ns_server
sudo ip netns add ns_client

# 3. Create the "Virtual Cable" (veth pair)
echo "Creating veth pair..."
sudo ip link add veth-server type veth peer name veth-client

# 4. Plug the ends into the namespaces
echo "Plugging cables in..."
sudo ip link set veth-server netns ns_server
sudo ip link set veth-client netns ns_client

# 5. Assign IP Addresses and Turn Interfaces ON
# Server gets .2, Client gets .1
echo "Configuring Server Interface (192.168.1.2)..."
sudo ip netns exec ns_server ip addr add 192.168.1.2/24 dev veth-server
sudo ip netns exec ns_server ip link set veth-server up
sudo ip netns exec ns_server ip link set lo up

echo "Configuring Client Interface (192.168.1.1)..."
sudo ip netns exec ns_client ip addr add 192.168.1.1/24 dev veth-client
sudo ip netns exec ns_client ip link set veth-client up
sudo ip netns exec ns_client ip link set lo up

# 6. Test Connectivity
echo "Testing connectivity..."
sudo ip netns exec ns_client ping -c 3 192.168.1.2